language: elixir
elixir:
  - 1.4
  - 1.5
otp_release:
  - 19.0
  - 20.0

sudo: false
notifications:
  email: false
services:
  - postgresql

env:
  - MIX_ENV=ci
before_script:
  - mix deps.get --only test
script:
  - mix test
