language: elixir
elixir:
  - 1.5
  - 1.6
  - 1.7
otp_release:
  - 19.0
  - 20.0
  - 21.0

sudo: false
notifications:
  email: false
services:
  - postgresql

env:
  - MIX_ENV=ci
before_script:
  - mix deps.get --only test
script:
  - mix test
